### PR TITLE
Auto generate srt filename

### PR DESCRIPTION
**Pull request by captn3m0**
I also switched the file loop with a single call to `file`.

### CODE REVIEW

**Comment by captn3m0** [comment]
@tunggnu Can this be merged?

**Review by tunggnu — CHANGES_REQUESTED** [review]
Hi, thank you for your improvement. For consistency, please make your message more meaningful:
exit ("vtt2srt file.vtt [file.srt]\n");

Anyway, the script name is webvtt2srt.php not vtt2srt

**Comment by captn3m0** [comment]
I had it aliased as vtt2srt since it makes it easier to remember and use. Added a usage message.

**Comment by tunggnu** [comment]
Thank you. Hope to work with you again in a near future.

**Pull request merged**
